from pathlib import Path
from uuid import UUID

from app.schemas.knowledge import KnowledgeDocumentSeed, KnowledgeType

LLMKNOWLEDGE_DIR = Path(__file__).resolve().parent


def read_knowledge_file(path: str) -> str:
    return (LLMKNOWLEDGE_DIR / path).read_text(encoding="utf-8")


REGISTRY: list[KnowledgeDocumentSeed] = [
    KnowledgeDocumentSeed(
        document_id=UUID("2626829d-bee5-51ff-94f4-92d7bd78c910"),
        doc_type=KnowledgeType.SKILL,
        priority="core",
        title="Manim Skill Overview",
        category="core",
        tags=[],
        path="manim_skill/SKILL.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("4ea2e34e-32c1-58ae-9060-8ae705d0eb3c"),
        doc_type=KnowledgeType.RULE,
        priority="core",
        title="Layout Composition",
        category="rules",
        tags=["layout", "composition", "frame", "positioning", "readability"],
        path="manim_skill/rules/layout-composition.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("bd9bb577-81f5-5ce1-969d-5a864f43c62e"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="3D",
        category="rules",
        tags=["3d"],
        path="manim_skill/rules/3d.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("b03f4678-eb4b-56b5-b926-edf60886287a"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Animation Groups",
        category="rules",
        tags=["animation", "groups"],
        path="manim_skill/rules/animation-groups.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("7b007669-d641-5f9b-958b-f69bc520c804"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Animations",
        category="rules",
        tags=["animations"],
        path="manim_skill/rules/animations.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("713b7b88-9443-5fbf-ab4b-03e64c0af589"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Axes",
        category="rules",
        tags=["axes"],
        path="manim_skill/rules/axes.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("e8614981-b80e-5815-9cb2-ae40e0699378"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Camera",
        category="rules",
        tags=["camera"],
        path="manim_skill/rules/camera.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("8ab50393-3dac-51a1-86fe-ae20016739b4"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="CLI",
        category="rules",
        tags=["cli"],
        path="manim_skill/rules/cli.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("54cdc928-a0c9-567c-9dc6-b250227c7437"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Colors",
        category="rules",
        tags=["colors"],
        path="manim_skill/rules/colors.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("a7c751e6-f9ff-58e4-addb-2cbe3bf6fd76"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Config",
        category="rules",
        tags=["config"],
        path="manim_skill/rules/config.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("e2c5cf48-c2f9-516a-9b10-6f3813689e02"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Creation Animations",
        category="rules",
        tags=["creation", "animations"],
        path="manim_skill/rules/creation-animations.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("383001f1-3d38-5081-b94b-797a0d7aba2a"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Educational Storyboarding",
        category="rules",
        tags=["educational", "storyboarding"],
        path="manim_skill/rules/educational-storyboarding.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("a7389fbd-0c95-50d2-99c0-ca812d8cd6b0"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Equation Transitions",
        category="rules",
        tags=["equation", "transitions"],
        path="manim_skill/rules/equation-transitions.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("9ae41aa7-7d60-5764-836b-ed69a56f4b90"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Graphing",
        category="rules",
        tags=["graphing"],
        path="manim_skill/rules/graphing.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("79eec5c8-fad7-5201-b67d-60cec1e3025a"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Grouping",
        category="rules",
        tags=["grouping"],
        path="manim_skill/rules/grouping.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("bc00b640-c72f-5945-a8dd-aad4b6bebf56"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="LaTeX",
        category="rules",
        tags=["latex"],
        path="manim_skill/rules/latex.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("cca8df70-9ff2-5457-85c7-ec5b21527625"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Lines",
        category="rules",
        tags=["lines"],
        path="manim_skill/rules/lines.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("c8836c15-83e3-5c6f-b904-5d942ba2dd2a"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Math Visual Clarity",
        category="rules",
        tags=["math", "visual", "clarity"],
        path="manim_skill/rules/math-visual-clarity.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("5a8aac5d-cb84-5c81-8a7d-d65ec7c1efd4"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Mobjects",
        category="rules",
        tags=["mobjects"],
        path="manim_skill/rules/mobjects.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("19d9d3b8-895e-5fdf-9977-46af6d096d56"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Positioning",
        category="rules",
        tags=["positioning"],
        path="manim_skill/rules/positioning.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("44b83051-e2d4-59b7-be38-337a6f1d0090"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Scenes",
        category="rules",
        tags=["scenes"],
        path="manim_skill/rules/scenes.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("22609bb1-06df-5deb-8516-a0803e205903"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Shapes",
        category="rules",
        tags=["shapes"],
        path="manim_skill/rules/shapes.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("ec002b09-a533-5d0a-9aba-5dc0b3536738"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Styling",
        category="rules",
        tags=["styling"],
        path="manim_skill/rules/styling.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("02f5a6dc-1ab0-519f-bda1-5d6cfb17e241"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Text Animations",
        category="rules",
        tags=["text", "animations"],
        path="manim_skill/rules/text-animations.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("d309e921-1ad5-5dad-a062-408849cd9bce"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Text",
        category="rules",
        tags=["text"],
        path="manim_skill/rules/text.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("3b036b93-ed4a-53de-b28e-0f415a9f0650"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Timing",
        category="rules",
        tags=["timing"],
        path="manim_skill/rules/timing.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("5c2ce180-8f28-5337-98bb-826bbf54511b"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Transform Animations",
        category="rules",
        tags=["transform", "animations"],
        path="manim_skill/rules/transform-animations.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("bea74d86-fe73-54a3-ab68-2812ecb40f9c"),
        doc_type=KnowledgeType.RULE,
        priority="recommended",
        title="Updaters",
        category="rules",
        tags=["updaters"],
        path="manim_skill/rules/updaters.md",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("b5d6ad11-568f-508e-8c53-094810a55cdc"),
        doc_type=KnowledgeType.TEMPLATE,
        priority="recommended",
        title="Basic Scene Template",
        category="templates",
        tags=["basic", "scene"],
        path="manim_skill/templates/basic_scene.py",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("eccb31c9-230d-5028-8617-5e64704bf132"),
        doc_type=KnowledgeType.TEMPLATE,
        priority="recommended",
        title="Camera Scene Template",
        category="templates",
        tags=["camera", "scene"],
        path="manim_skill/templates/camera_scene.py",
    ),
    KnowledgeDocumentSeed(
        document_id=UUID("59fe067e-f8af-5d89-aeb2-2d06b8e1c674"),
        doc_type=KnowledgeType.TEMPLATE,
        priority="recommended",
        title="3D Scene Template",
        category="templates",
        tags=["3d", "scene"],
        path="manim_skill/templates/threed_scene.py",
    ),
]

REGISTRY_BY_ID: dict[UUID, KnowledgeDocumentSeed] = {
    entry.document_id: entry for entry in REGISTRY
}

CORE_DOCUMENTS: list[KnowledgeDocumentSeed] = [
    entry for entry in REGISTRY if entry.priority == "core"
]
