from manim import *


class Scene1(Scene):
    def construct(self):
        title_group = VGroup()
        middle_group = VGroup()
        bottom_group = VGroup()

        title = Text("Solve by Substitution")
        title.to_edge(UP)
        title_group.add(title)
        self.play(Write(title), run_time=2)
        self.wait(1.5)

        eq1 = MathTex("y", "=", "2x", "+", "1")
        eq1.scale(1.0)
        eq2 = MathTex("x", "+", "y", "=", "7")
        eq2.scale(1.0)
        system_block = VGroup(eq1, eq2)
        system_block.arrange(direction=DOWN, buff=0.6)
        system_block.move_to(UP * 1.6)
        middle_group.add(system_block)
        self.play(Write(system_block), run_time=0.8)
        self.wait(2)

        eq1_highlight = MathTex("y", "=", "2x", "+", "1")
        eq1_highlight.scale(1.0)
        eq1_highlight.set_color_by_tex("y", BLUE_E)
        eq2_highlight = MathTex("x", "+", "y", "=", "7")
        eq2_highlight.scale(1.0)
        eq2_highlight.set_color_by_tex("y", BLUE_E)
        highlighted_block = VGroup(eq1_highlight, eq2_highlight)
        highlighted_block.arrange(direction=DOWN, buff=0.6)
        highlighted_block.move_to(UP * 1.6)
        middle_group.add(highlighted_block)
        self.play(ReplacementTransform(system_block, highlighted_block), run_time=0.8)
        middle_group.remove(system_block)
        self.wait(2)

        eq1_sub = MathTex("y", "=", "2x", "+", "1")
        eq1_sub.scale(1.0)
        eq2_sub = MathTex("x", "+", "(", "2x", "+", "1", ")", "=", "7")
        eq2_sub.scale(1.0)
        substituted_block = VGroup(eq1_sub, eq2_sub)
        substituted_block.arrange(direction=DOWN, buff=0.6)
        substituted_block.move_to(UP * 1.6)
        middle_group.add(substituted_block)
        self.play(ReplacementTransform(highlighted_block, substituted_block), run_time=0.8)
        middle_group.remove(highlighted_block)
        self.wait(2)

        simplified_eq = MathTex("3x", "+", "1", "=", "7")
        simplified_eq.scale(1.1)
        simplified_eq.move_to(UP * 1.6)
        middle_group.add(simplified_eq)
        self.play(ReplacementTransform(substituted_block, simplified_eq), run_time=0.8)
        middle_group.remove(substituted_block)
        self.wait(1)

        final_scene1 = MathTex("3x", "+", "1", "=", "7", color=GREEN)
        final_scene1.scale(1.0)
        final_scene1.to_edge(DOWN)
        bottom_group.add(final_scene1)
        self.play(TransformFromCopy(simplified_eq, final_scene1), run_time=0.8)
        self.wait(1)

        self.play(FadeOut(title_group), FadeOut(middle_group), FadeOut(bottom_group), run_time=0.8)
        self.wait(1)


class Scene2(Scene):
    def construct(self):
        title_group = VGroup()
        middle_group = VGroup()
        bottom_group = VGroup()

        title = Text("Finish and Solve")
        title.to_edge(UP)
        title_group.add(title)
        self.play(Write(title), run_time=2)
        self.wait(1.5)

        eq_start = MathTex("3x", "+", "1", "=", "7")
        eq_start.scale(1.1)
        eq_start.move_to(UP * 2)
        middle_group.add(eq_start)
        self.play(Write(eq_start), run_time=0.8)
        self.wait(2)

        cue_minus = MathTex("/", "-", "1")
        cue_minus.scale(1.0)
        cue_minus.set_color(ORANGE)
        cue_minus.next_to(eq_start, RIGHT, buff=0.8)
        self.play(FadeIn(cue_minus), run_time=0.8)
        self.wait(1)

        eq_subtract = MathTex("3x", "=", "6")
        eq_subtract.scale(1.1)
        eq_subtract.move_to(UP * 2)
        middle_group.add(eq_subtract)
        self.play(ReplacementTransform(eq_start, eq_subtract), FadeOut(cue_minus), run_time=0.8)
        middle_group.remove(eq_start)
        self.wait(2)

        cue_divide = MathTex("/","\\div", "3")
        cue_divide.scale(1.0)
        cue_divide.set_color(ORANGE)
        cue_divide.next_to(eq_subtract, RIGHT, buff=0.8)
        self.play(FadeIn(cue_divide), run_time=0.8)
        self.wait(1)

        eq_x = MathTex("x", "=", "2")
        eq_x.scale(1.1)
        eq_x.move_to(UP * 2)
        middle_group.add(eq_x)
        self.play(ReplacementTransform(eq_subtract, eq_x), FadeOut(cue_divide), run_time=0.8)
        middle_group.remove(eq_subtract)
        self.wait(2)

        eq_y_base = MathTex("y", "=", "2", "x", "+", "1")
        eq_y_base.scale(1.0)
        eq_y_base.next_to(eq_x, DOWN, buff=0.8)
        middle_group.add(eq_y_base)
        self.play(Write(eq_y_base), run_time=0.8)
        self.wait(2)

        eq_x_link = MathTex("x", "=", "2")
        eq_x_link.scale(1.1)
        eq_x_link.set_color_by_tex("x", BLUE_E)
        eq_x_link.move_to(UP * 2)
        eq_y_link = MathTex("y", "=", "2", "x", "+", "1")
        eq_y_link.scale(1.0)
        eq_y_link.set_color_by_tex("x", BLUE_E)
        eq_y_link.next_to(eq_x_link, DOWN, buff=0.8)
        link_block = VGroup(eq_x_link, eq_y_link)
        middle_group.add(link_block)
        self.play(
            ReplacementTransform(eq_x, eq_x_link),
            ReplacementTransform(eq_y_base, eq_y_link),
            run_time=0.8,
        )
        middle_group.remove(eq_x, eq_y_base)
        self.wait(1)

        eq_y_sub = MathTex("y", "=", "2", "(", "2", ")", "+", "1")
        eq_y_sub.scale(1.0)
        eq_y_sub.next_to(eq_x_link, DOWN, buff=0.8)
        middle_group.add(eq_y_sub)
        self.play(ReplacementTransform(eq_y_link, eq_y_sub), run_time=0.8)
        link_block.remove(eq_y_link)
        self.wait(1)

        eq_y_final = MathTex("y", "=", "5")
        eq_y_final.scale(1.0)
        eq_y_final.next_to(eq_x_link, DOWN, buff=0.8)
        middle_group.add(eq_y_final)
        self.play(ReplacementTransform(eq_y_sub, eq_y_final), run_time=0.8)
        middle_group.remove(eq_y_sub)
        self.wait(1)

        solution = MathTex("(", "2", ",", "5", ")", color=GREEN)
        solution.scale(1.1)
        solution.to_edge(DOWN)
        bottom_group.add(solution)
        self.play(TransformFromCopy(VGroup(eq_x_link, eq_y_final), solution), run_time=0.8)
        self.wait(1)

        self.play(FadeOut(title_group), FadeOut(middle_group), FadeOut(bottom_group), run_time=0.8)
        self.wait(1)
