from manim import *


class Scene1(Scene):
    def construct(self):
        title_group = VGroup()
        middle_group = VGroup()
        bottom_group = VGroup()

        title = Text("What the Limit Approaches")
        title.to_edge(UP)
        title_group.add(title)
        self.play(Write(title, run_time=2))
        self.wait(1.5)

        limit_expression = MathTex(r"\lim_{x\to2} f(x)=4", color=BLUE)
        limit_expression.move_to(UP * 2)
        middle_group.add(limit_expression)
        self.play(Write(limit_expression, run_time=0.8))
        self.wait(2)

        plane = NumberPlane(x_range=[0, 4, 1], y_range=[2, 6, 1])
        plane.scale(0.8)
        plane.next_to(limit_expression, DOWN, buff=0.5)
        middle_group.add(plane)
        self.play(Create(plane, run_time=0.8))
        self.wait(2)

        graph_left = ParametricFunction(
            lambda t: plane.coords_to_point(t, t + 2),
            t_range=[0, 1.95],
        )
        graph_right = ParametricFunction(
            lambda t: plane.coords_to_point(t, t + 2),
            t_range=[2.05, 4],
        )
        graph_block = VGroup(graph_left, graph_right)
        middle_group.add(graph_block)
        self.play(Create(graph_block, run_time=0.8))
        self.wait(2)

        hole_marker = MathTex(r"\circ")
        hole_marker.move_to(plane.coords_to_point(2, 4))
        hole_label = MathTex(r"(2,4)")
        hole_label.scale(0.8)
        hole_label.next_to(hole_marker, UP, buff=0.5)
        hole_block = VGroup(hole_marker, hole_label)
        middle_group.add(hole_block)
        self.play(FadeIn(hole_block, run_time=0.8))
        self.wait(2)

        left_dot = Dot(plane.coords_to_point(1.85, 3.85))
        left_note = MathTex(r"x\to2^-", color=BLUE)
        left_note.scale(0.8)
        left_note.next_to(left_dot, LEFT, buff=0.25)
        left_block = VGroup(left_dot, left_note)
        middle_group.add(left_block)
        self.play(FadeIn(left_block, run_time=0.8))
        self.wait(2)

        right_dot = Dot(plane.coords_to_point(2.15, 4.15))
        right_note = MathTex(r"x\to2^+", color=BLUE)
        right_note.scale(0.8)
        right_note.next_to(right_dot, RIGHT, buff=0.25)
        right_block = VGroup(right_dot, right_note)
        middle_group.add(right_block)
        self.play(ReplacementTransform(left_block, right_block, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(limit_expression)
        middle_group.add(plane)
        middle_group.add(graph_block)
        middle_group.add(hole_block)
        middle_group.add(right_block)
        self.wait(2)

        final_result = MathTex(r"\lim_{x\to2} f(x)=4", color=GREEN)
        final_result.to_edge(DOWN)
        bottom_group.add(final_result)
        self.play(TransformFromCopy(limit_expression, final_result, run_time=0.8))
        self.wait(1)

        self.play(FadeOut(title_group), FadeOut(middle_group), FadeOut(bottom_group), run_time=0.8)
        self.wait(1)


class Scene2(Scene):
    def construct(self):
        title_group = VGroup()
        middle_group = VGroup()
        bottom_group = VGroup()

        title = Text("Simplify Before Substituting")
        title.to_edge(UP)
        title_group.add(title)
        self.play(Write(title, run_time=2))
        self.wait(1.5)

        example1 = MathTex(r"\lim_{x\to2}\frac{x^2-4}{x-2}")
        example1.scale(0.9)
        example1.move_to(UP * 2)
        middle_group.add(example1)
        self.play(Write(example1, run_time=0.8))
        self.wait(2)

        substitution1 = MathTex(r"\lim_{x\to2}\frac{2^2-4}{2-2}")
        substitution1.scale(0.9)
        substitution1.move_to(example1)
        middle_group.add(substitution1)
        self.play(ReplacementTransform(example1, substitution1, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(substitution1)
        self.wait(1)

        indeterminate1_rhs = MathTex(r"=\frac{0}{0}", color=RED)
        indeterminate1_rhs.scale(0.9)
        indeterminate1_rhs.next_to(substitution1, RIGHT, buff=0.3)
        middle_group.add(indeterminate1_rhs)
        self.play(Write(indeterminate1_rhs, run_time=0.8))
        substitution1_block = VGroup(substitution1, indeterminate1_rhs)
        middle_group = VGroup()
        middle_group.add(substitution1_block)
        self.wait(1)

        factored1 = MathTex(r"\lim_{x\to2}","{(","x-2",")(x+2)",r"\over","x-2","}")
        factored1.scale(0.9)
        factored1.move_to(substitution1)
        middle_group.add(factored1)
        self.play(ReplacementTransform(substitution1_block, factored1, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(factored1)
        self.wait(1)

        self.play(factored1.get_parts_by_tex("x-2").animate.set_color(BLUE), run_time=0.8)
        self.wait(1)

        simplified1 = MathTex(r"\lim_{x\to2}(x+2)")
        simplified1.scale(0.9)
        simplified1.move_to(factored1)
        middle_group.add(simplified1)
        self.play(ReplacementTransform(factored1, simplified1, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(simplified1)
        self.wait(1)

        substitution1_simple = MathTex(r"\lim_{x\to2}(2+2)")
        substitution1_simple.scale(0.9)
        substitution1_simple.move_to(simplified1)
        middle_group.add(substitution1_simple)
        self.play(ReplacementTransform(simplified1, substitution1_simple, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(substitution1_simple)
        self.wait(1)

        answer1_rhs = MathTex(r"=4", color=GREEN)
        answer1_rhs.scale(0.9)
        answer1_rhs.next_to(substitution1_simple, RIGHT, buff=0.3)
        middle_group.add(answer1_rhs)
        self.play(Write(answer1_rhs, run_time=0.8))
        result1 = VGroup(substitution1_simple, answer1_rhs)
        middle_group = VGroup()
        middle_group.add(result1)
        self.wait(1)

        example2 = MathTex(r"\lim_{x\to1}\frac{x^2-1}{x-1}")
        example2.scale(0.9)
        example2.next_to(result1, DOWN, buff=0.5)
        middle_group.add(example2)
        self.play(Write(example2, run_time=0.8))
        self.wait(2)

        substitution2 = MathTex(r"\lim_{x\to1}\frac{1^2-1}{1-1}")
        substitution2.scale(0.9)
        substitution2.move_to(example2)
        middle_group.add(substitution2)
        self.play(ReplacementTransform(example2, substitution2, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(result1)
        middle_group.add(substitution2)
        self.wait(1)

        indeterminate2_rhs = MathTex(r"=\frac{0}{0}", color=RED)
        indeterminate2_rhs.scale(0.9)
        indeterminate2_rhs.next_to(substitution2, RIGHT, buff=0.3)
        middle_group.add(indeterminate2_rhs)
        self.play(Write(indeterminate2_rhs, run_time=0.8))
        substitution2_block = VGroup(substitution2, indeterminate2_rhs)
        middle_group = VGroup()
        middle_group.add(result1)
        middle_group.add(substitution2_block)
        self.wait(1)

        factored2 = MathTex(r"\lim_{x\to1}", "{(", "x-1", ")(x+1)", r"\over", "x-1", "}")
        factored2.scale(0.9)
        factored2.move_to(substitution2)
        middle_group.add(factored2)
        self.play(ReplacementTransform(substitution2_block, factored2, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(result1)
        middle_group.add(factored2)
        self.wait(1)
        self.play(factored2.get_parts_by_tex("x-1").animate.set_color(BLUE), run_time=0.8)
        self.wait(1)

        simplified2 = MathTex(r"\lim_{x\to1}(x+1)")
        simplified2.scale(0.9)
        simplified2.move_to(factored2)
        middle_group.add(simplified2)
        self.play(ReplacementTransform(factored2, simplified2, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(result1)
        middle_group.add(simplified2)
        self.wait(1)

        substitution2_simple = MathTex(r"\lim_{x\to1}(1+1)")
        substitution2_simple.scale(0.9)
        substitution2_simple.move_to(simplified2)
        middle_group.add(substitution2_simple)
        self.play(ReplacementTransform(simplified2, substitution2_simple, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(result1)
        middle_group.add(substitution2_simple)
        self.wait(1)

        answer2_rhs = MathTex(r"=2", color=GREEN)
        answer2_rhs.scale(0.9)
        answer2_rhs.next_to(substitution2_simple, RIGHT, buff=0.3)
        middle_group.add(answer2_rhs)
        self.play(Write(answer2_rhs, run_time=0.8))
        result2 = VGroup(substitution2_simple, answer2_rhs)
        middle_group = VGroup()
        middle_group.add(result1)
        middle_group.add(result2)
        self.wait(1)

        final_result = MathTex(r"\lim_{x\to2}\frac{x^2-4}{x-2}=4,\ \lim_{x\to1}\frac{x^2-1}{x-1}=2", color=GREEN)
        final_result.scale(0.75)
        final_result.to_edge(DOWN)
        bottom_group.add(final_result)
        result_block = VGroup(result1, result2)
        self.play(TransformFromCopy(result_block, final_result, run_time=0.8))
        self.wait(1)

        self.play(FadeOut(title_group), FadeOut(middle_group), FadeOut(bottom_group), run_time=0.8)
        self.wait(1)
