from manim import *


class Scene1(Scene):
    def construct(self):
        title_group = VGroup()
        middle_group = VGroup()
        bottom_group = VGroup()

        title = Text("Differentiate with the Power Rule")
        title.scale(0.8)
        title.to_edge(UP)
        title_group.add(title)
        self.play(Write(title, run_time=2))
        self.wait(1.5)

        rule = MathTex(r"{d\over dx}(x^n)=n x^{n-1}", color=BLUE)
        rule.scale(0.9)
        rule.move_to(UP * 2)
        middle_group.add(rule)
        self.play(Write(rule, run_time=0.8))
        self.wait(2)

        function_eq = MathTex(r"f(x)=3x^4-2x^2+5")
        function_eq.scale(0.9)
        function_eq.next_to(rule, DOWN, buff=0.5)
        middle_group.add(function_eq)
        self.play(Write(function_eq, run_time=0.8))
        self.wait(2)

        term1 = MathTex(r"{d\over dx}(3x^4)=12x^3", color=BLUE)
        term1.scale(0.75)
        term2 = MathTex(r"{d\over dx}(-2x^2)=-4x", color=BLUE)
        term2.scale(0.75)
        term3 = MathTex(r"{d\over dx}(5)=0", color=BLUE)
        term3.scale(0.75)
        terms_row = VGroup(term1, term2, term3)
        terms_row.arrange(direction=RIGHT, buff=0.55)
        terms_row.next_to(function_eq, DOWN, buff=0.45)
        middle_group.add(term1)
        self.play(TransformFromCopy(function_eq, term1, run_time=0.8))
        self.wait(1)

        middle_group.add(term2)
        self.play(TransformFromCopy(function_eq, term2, run_time=0.8))
        self.wait(1)

        middle_group.add(term3)
        self.play(TransformFromCopy(function_eq, term3, run_time=0.8))
        self.wait(1)

        self.play(FadeOut(function_eq, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(rule)
        middle_group.add(term1)
        middle_group.add(term2)
        middle_group.add(term3)
        self.wait(1)

        combined_eq = MathTex(r"f'(x)=12x^3-4x+0")
        combined_eq.scale(0.9)
        combined_eq.next_to(rule, DOWN, buff=0.5)
        middle_group.add(combined_eq)
        terms_block = VGroup(term1, term2, term3)
        self.play(TransformFromCopy(terms_block, combined_eq, run_time=0.8))
        self.wait(1)

        self.play(FadeOut(terms_block, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(rule)
        middle_group.add(combined_eq)
        self.wait(2)

        simplified_eq = MathTex(r"f'(x)=12x^3-4x")
        simplified_eq.scale(0.9)
        simplified_eq.move_to(combined_eq)
        middle_group.add(simplified_eq)
        self.play(ReplacementTransform(combined_eq, simplified_eq, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(rule)
        middle_group.add(simplified_eq)
        self.wait(1)

        final_result = MathTex(r"f'(x)=12x^3-4x", color=GREEN)
        final_result.scale(0.9)
        final_result.to_edge(DOWN)
        bottom_group.add(final_result)
        self.play(TransformFromCopy(simplified_eq, final_result, run_time=0.8))
        self.wait(1)

        self.play(FadeOut(title_group), FadeOut(middle_group), FadeOut(bottom_group), run_time=0.8)
        self.wait(1)


class Scene2(Scene):
    def construct(self):
        title_group = VGroup()
        middle_group = VGroup()
        bottom_group = VGroup()

        title = Text("Common Derivative Errors")
        title.scale(0.9)
        title.to_edge(UP)
        title_group.add(title)
        self.play(Write(title, run_time=2))
        self.wait(1.5)

        rule = MathTex(r"{d\over dx}(x^n)=n x^{n-1}", color=BLUE)
        rule.scale(0.9)
        rule.move_to(UP * 2)
        middle_group.add(rule)
        self.play(Write(rule, run_time=0.8))
        self.wait(2)

        wrong_first = MathTex(r"3x^4\to2x^3", color=RED)
        wrong_first.scale(0.9)
        wrong_first.next_to(rule, DOWN, buff=0.5)
        middle_group.add(wrong_first)
        self.play(Write(wrong_first, run_time=0.8))
        self.wait(2)

        correct_first = MathTex(r"3x^4\to12x^3", color=BLUE)
        correct_first.scale(0.9)
        correct_first.move_to(wrong_first)
        middle_group.add(correct_first)
        self.play(ReplacementTransform(wrong_first, correct_first, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(rule)
        middle_group.add(correct_first)
        self.wait(1)

        function_g = MathTex(r"g(x)=-5x^3+4")
        function_g.scale(0.9)
        function_g.next_to(correct_first, DOWN, buff=0.6)
        middle_group.add(function_g)
        self.play(Write(function_g, run_time=0.8))
        self.wait(2)

        wrong_second = MathTex(r"g'(x)=15x^2", color=RED)
        wrong_second.scale(0.9)
        wrong_second.next_to(function_g, DOWN, buff=0.5)
        middle_group.add(wrong_second)
        self.play(Write(wrong_second, run_time=0.8))
        self.wait(2)

        sign_check = MathTex(r"(-5)\cdot3=-15", color=BLUE)
        sign_check.scale(0.9)
        sign_check.next_to(wrong_second, DOWN, buff=0.45)
        middle_group.add(sign_check)
        self.play(TransformFromCopy(function_g, sign_check, run_time=0.8))
        self.wait(1)

        correct_second = MathTex(r"g'(x)=-15x^2", color=BLUE)
        correct_second.scale(0.9)
        correct_second.move_to(wrong_second)
        middle_group.add(correct_second)
        self.play(ReplacementTransform(wrong_second, correct_second, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(rule)
        middle_group.add(correct_first)
        middle_group.add(function_g)
        middle_group.add(correct_second)
        middle_group.add(sign_check)
        self.wait(1)

        final_result = MathTex(r"3x^4\to12x^3,\ g'(x)=-15x^2+4", color=GREEN)
        final_result.scale(0.85)
        final_result.to_edge(DOWN)
        bottom_group.add(final_result)
        corrected_block = VGroup(correct_first, correct_second)
        self.play(TransformFromCopy(corrected_block, final_result, run_time=0.8))
        self.wait(1)

        self.play(FadeOut(title_group), FadeOut(middle_group), FadeOut(bottom_group), run_time=0.8)
        self.wait(1)
