from manim import *


class Scene1(Scene):
    def construct(self):
        title_group = VGroup()
        middle_group = VGroup()
        bottom_group = VGroup()

        title = Text("Find Critical x-Values")
        title.to_edge(UP)
        title_group.add(title)
        self.play(Write(title, run_time=2))
        self.wait(1.5)
        self.wait(0.5)

        rule = MathTex(r"f'(x)=0\ \lor\ \nexists f'(x)")
        rule.move_to(UP * 2)
        middle_group.add(rule)
        self.play(Write(rule, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        function_eq = MathTex(r"f(x)=x^3-6x^2+9x")
        function_eq.next_to(rule, DOWN, buff=0.5)
        middle_group.add(function_eq)
        self.play(Write(function_eq, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        derivative_eq = MathTex(r"f'(x)=3x^2-12x+9", color=BLUE)
        derivative_eq.move_to(function_eq)
        middle_group.add(derivative_eq)
        self.play(ReplacementTransform(function_eq, derivative_eq, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(rule)
        middle_group.add(derivative_eq)
        self.wait(1)
        self.wait(0.5)

        zero_eq = MathTex(r"3x^2-12x+9=0")
        zero_eq.move_to(derivative_eq)
        middle_group.add(zero_eq)
        self.play(ReplacementTransform(derivative_eq, zero_eq, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(rule)
        middle_group.add(zero_eq)
        self.wait(1)
        self.wait(0.5)

        divide_separator = MathTex(r"/", color=ORANGE)
        divide_action = MathTex(r"\div 3", color=ORANGE)
        divide_action.next_to(divide_separator, RIGHT, buff=0.5)
        divide_marker = VGroup(divide_separator, divide_action)
        divide_marker.next_to(zero_eq, RIGHT, buff=0.5)
        zero_with_marker = VGroup(zero_eq, divide_marker)
        middle_group = VGroup()
        middle_group.add(rule)
        middle_group.add(zero_with_marker)
        self.play(Write(divide_marker, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        simplified_eq = MathTex(r"x^2-4x+3=0")
        simplified_eq.move_to(zero_eq)
        middle_group.add(simplified_eq)
        self.play(ReplacementTransform(zero_with_marker, simplified_eq, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(rule)
        middle_group.add(simplified_eq)
        self.wait(1)
        self.wait(0.5)

        final_result = MathTex(r"x^2-4x+3=0", color=GREEN)
        final_result.to_edge(DOWN)
        bottom_group.add(final_result)
        self.play(TransformFromCopy(simplified_eq, final_result, run_time=0.8))
        self.wait(1)
        self.wait(0.5)

        self.play(FadeOut(title_group), FadeOut(middle_group), FadeOut(bottom_group), run_time=0.8)
        self.wait(1)


class Scene2(Scene):
    def construct(self):
        title_group = VGroup()
        middle_group = VGroup()
        bottom_group = VGroup()

        title = Text("Solve for the Critical x-Values")
        title.to_edge(UP)
        title_group.add(title)
        self.play(Write(title, run_time=2))
        self.wait(1.5)
        self.wait(0.5)

        equation = MathTex(r"x^2-4x+3=0")
        equation.move_to(UP * 2)
        middle_group.add(equation)
        self.play(Write(equation, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        factored_eq = MathTex(r"(x-1)(x-3)=0", color=BLUE)
        factored_eq.move_to(equation)
        middle_group.add(factored_eq)
        self.play(ReplacementTransform(equation, factored_eq, run_time=0.8))
        middle_group = VGroup()
        middle_group.add(factored_eq)
        self.wait(1)
        self.wait(0.5)

        solution_one = MathTex(r"x=1")
        solution_three = MathTex(r"x=3")
        solutions_block = VGroup(solution_one, solution_three)
        solutions_block.arrange(direction=RIGHT, buff=1)
        solutions_block.next_to(factored_eq, DOWN, buff=0.5)
        middle_group.add(solutions_block)
        self.play(TransformFromCopy(factored_eq, solutions_block, run_time=0.8))
        self.wait(1)
        self.wait(0.5)

        number_line = NumberLine(x_range=[0, 4, 1])
        number_line.scale(0.7)
        number_line.next_to(solutions_block, DOWN, buff=0.5)
        middle_group.add(number_line)
        self.play(Create(number_line, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        point_one_dot = Dot(number_line.n2p(1))
        point_one_label = MathTex(r"x=1")
        point_one_label.next_to(point_one_dot, DOWN, buff=0.5)
        point_one_block = VGroup(point_one_dot, point_one_label)
        middle_group.add(point_one_block)
        self.play(FadeIn(point_one_block, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        point_three_dot = Dot(number_line.n2p(3))
        point_three_label = MathTex(r"x=3")
        point_three_label.next_to(point_three_dot, DOWN, buff=0.5)
        point_three_block = VGroup(point_three_dot, point_three_label)
        middle_group.add(point_three_block)
        self.play(FadeIn(point_three_block, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        final_result = MathTex(r"x=1,\ x=3", color=GREEN)
        final_result.to_edge(DOWN)
        bottom_group.add(final_result)
        self.play(TransformFromCopy(solutions_block, final_result, run_time=0.8))
        self.wait(1)
        self.wait(0.5)

        self.play(FadeOut(title_group), FadeOut(middle_group), FadeOut(bottom_group), run_time=0.8)
        self.wait(1)


class Scene3(Scene):
    def construct(self):
        title_group = VGroup()
        middle_group = VGroup()
        bottom_group = VGroup()

        title = Text("Turn Critical x-Values into Points")
        title.to_edge(UP)
        title_group.add(title)
        self.play(Write(title, run_time=2))
        self.wait(1.5)
        self.wait(0.5)

        function_eq = MathTex(r"f(x)=x^3-6x^2+9x")
        function_eq.move_to(UP * 2)
        middle_group.add(function_eq)
        self.play(Write(function_eq, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        x_one = MathTex(r"x=1")
        x_three = MathTex(r"x=3")
        x_values = VGroup(x_one, x_three)
        x_values.arrange(direction=RIGHT, buff=1)
        x_values.next_to(function_eq, DOWN, buff=0.5)
        middle_group.add(x_values)
        self.play(Write(x_values, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        eval_one = MathTex(r"f(1)=1-6+9=4", color=BLUE)
        eval_one.next_to(x_values, DOWN, buff=0.5)
        middle_group.add(eval_one)
        self.play(TransformFromCopy(function_eq, eval_one, run_time=0.8))
        self.wait(1)
        self.wait(0.5)

        eval_three = MathTex(r"f(3)=27-54+27=0", color=BLUE)
        eval_three.next_to(eval_one, DOWN, buff=0.5)
        middle_group.add(eval_three)
        self.play(TransformFromCopy(function_eq, eval_three, run_time=0.8))
        self.wait(1)
        self.wait(0.5)

        self.play(FadeOut(middle_group), run_time=0.8)
        middle_group = VGroup()
        self.wait(0.5)

        plane = NumberPlane(x_range=[-1, 4, 1], y_range=[-1, 5, 1])
        plane.scale(0.8)
        plane.move_to(ORIGIN)
        middle_group.add(plane)
        self.play(Create(plane, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        curve = ParametricFunction(
            lambda t: plane.coords_to_point(t, t**3 - 6 * t**2 + 9 * t),
            t_range=[0, 4],
        )
        middle_group.add(curve)
        self.play(Create(curve, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        point_one_dot = Dot(plane.coords_to_point(1, 4))
        point_one_label = MathTex(r"(1,4)")
        point_one_label.next_to(point_one_dot, UP, buff=0.5)
        point_one_block = VGroup(point_one_dot, point_one_label)
        middle_group.add(point_one_block)
        self.play(FadeIn(point_one_block, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        point_three_dot = Dot(plane.coords_to_point(3, 0))
        point_three_label = MathTex(r"(3,0)")
        point_three_label.next_to(point_three_dot, DOWN, buff=0.5)
        point_three_block = VGroup(point_three_dot, point_three_label)
        middle_group.add(point_three_block)
        self.play(FadeIn(point_three_block, run_time=0.8))
        self.wait(2)
        self.wait(0.5)

        final_result = MathTex(r"(1,4),\ (3,0)", color=GREEN)
        final_result.to_edge(DOWN)
        bottom_group.add(final_result)
        points_block = VGroup(point_one_block, point_three_block)
        self.play(TransformFromCopy(points_block, final_result, run_time=0.8))
        self.wait(1)
        self.wait(0.5)

        self.play(FadeOut(title_group), FadeOut(middle_group), FadeOut(bottom_group), run_time=0.8)
        self.wait(1)
