#!/usr/bin/env bash
# provision-secrets.sh — Create Secrets Manager entries for a given environment
#
# Run ONCE before the first deploy. The script is idempotent: if a secret
# already exists it prints a skip message and continues. It does NOT overwrite
# existing values — use the AWS Console or CLI to rotate secrets.
#
# Usage: ./provision-secrets.sh <env> <region>
#
# Example:
#   ./provision-secrets.sh prod eu-north-1
#
# Secrets created:
#   mathanimate/<env>/db-password       — generated by Terraform; this script ensures
#                                   the other secrets exist with placeholder values
#                                   so operators can fill them in.
#   mathanimate/<env>/api-key           — API authentication key (fill in after creation)
#   mathanimate/<env>/storage-access-key — S3/IAM access key (or leave blank for role-based access)
#   mathanimate/<env>/storage-secret-key — S3/IAM secret key (or leave blank for role-based access)

set -euo pipefail

# ── Argument validation ────────────────────────────────────────────────────────
if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <env> <region>" >&2
  exit 1
fi

ENV="$1"
REGION="$2"

echo "==> Provisioning Secrets Manager entries for env=${ENV} region=${REGION}"
echo ""

# ── Helper: create secret if it doesn't exist ─────────────────────────────────
create_secret_if_missing() {
  local secret_name="$1"
  local description="$2"
  local initial_value="$3"

  if aws secretsmanager describe-secret \
    --region "${REGION}" \
    --secret-id "${secret_name}" &>/dev/null 2>&1; then
    echo "    [SKIP] ${secret_name} already exists"
    return 0
  fi

  aws secretsmanager create-secret \
    --region "${REGION}" \
    --name "${secret_name}" \
    --description "${description}" \
    --secret-string "${initial_value}" \
    --tags "[{\"Key\":\"Project\",\"Value\":\"math-animate\"},{\"Key\":\"Environment\",\"Value\":\"${ENV}\"}]" \
    --output text --query "ARN" | xargs -I{} echo "    [OK]  Created: {}"
}

# ── db-password ────────────────────────────────────────────────────────────────
# Terraform generates and manages the actual password. We create a placeholder
# here so the secret path is registered. Terraform will update the value on apply.
DB_PASSWORD_PLACEHOLDER=$(python3 -c "import secrets,string; print(secrets.token_urlsafe(32))" 2>/dev/null || \
  openssl rand -base64 32 | tr -d "=+/" | head -c 32)

create_secret_if_missing \
  "mathanimate/${ENV}/db-password" \
  "RDS PostgreSQL master password — managed by Terraform, do not edit manually" \
  "${DB_PASSWORD_PLACEHOLDER}"

# ── api-key ────────────────────────────────────────────────────────────────────
API_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))" 2>/dev/null || \
  openssl rand -base64 48 | tr -d "=+/" | head -c 48)

create_secret_if_missing \
  "mathanimate/${ENV}/api-key" \
  "API authentication key for the MathAnimate REST API" \
  "${API_KEY}"

# ── storage-access-key ─────────────────────────────────────────────────────────
# When the API runs on ECS with an IAM task role, the application uses the role
# credentials automatically. These secrets can be left as empty strings in that
# case — the boto3/s3 client will fall through to the IAM credential chain.
create_secret_if_missing \
  "mathanimate/${ENV}/storage-access-key" \
  "S3 access key (leave empty when using IAM task role)" \
  ""

# ── storage-secret-key ─────────────────────────────────────────────────────────
create_secret_if_missing \
  "mathanimate/${ENV}/storage-secret-key" \
  "S3 secret key (leave empty when using IAM task role)" \
  ""

echo ""
echo "==> Secret provisioning complete."
echo ""
echo "    IMPORTANT: Review and update the following secrets in the AWS Console"
echo "    or via 'aws secretsmanager put-secret-value' before starting the app:"
echo ""
echo "    1. mathanimate/${ENV}/api-key           — auto-generated, save this value"
echo "    2. mathanimate/${ENV}/storage-access-key — set only if NOT using IAM task role"
echo "    3. mathanimate/${ENV}/storage-secret-key — set only if NOT using IAM task role"
echo ""
echo "    The api-key that was generated:"
API_KEY_CURRENT=$(aws secretsmanager get-secret-value \
  --region "${REGION}" \
  --secret-id "mathanimate/${ENV}/api-key" \
  --query SecretString --output text 2>/dev/null || echo "(could not read)")
echo "    ${API_KEY_CURRENT}"
